name = "AILeetcode"
uuid = "30baf41b-da27-4431-bfba-f7daafb094fd"
authors = ["anand jain <anandj@uchicago.edu>"]
version = "0.1.0"

[deps]
OpenAIReplMode = "022fafc6-85a1-46a3-9dea-7935d3763744"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
